### ISSUE TITLE
unable to execute understanding Token Transfer file steps 

### ISSUE THREAD

**Issue by HelmiTrabelsi** [TokenySolutions/T-REX#122]
when I execute this cmd "claimIssuerContract = await ClaimHolder.new({ from: claimIssuer });"  in the truffle console, I got this error "ClaimHolder is not defined" and I cannot find a smart contract with this name.

**Comment by Nakasar** [comment]
Hi @HelmiTrabelsi !

I think `ClaimHolder` should be `ClaimIssuer` in the command you are attempting to execute. We might have a type in our documentation, where did you find this command?

The `ClaimIssuer` contract is part of ONCHAINID suite (https://github.com/onchain-id/solidity/blob/main/contracts/ClaimIssuer.sol).

**Comment by Joachim-Lebrun** [comment]
`ClaimHolder` is an `Identity.sol` contract, while `ClaimIssuer` is a `ClaimIssuer.sol` contract from the ONCHAINID repository, note that `ClaimIssuer.sol` is inheriting from `Identity.sol` therefore a `ClaimIssuer` can also be used as a `ClaimHolder` contract
