### ISSUE TITLE
is T-REX 4 releasing anytime soon?

### ISSUE THREAD

**Issue by sthapa-nyala** [TokenySolutions/T-REX#123]
I can see there was a beta release for 4-0-0. Any plans for the official final release? 

Thanks

**Comment by sthapa-nyala** [comment]
@Joachim-Lebrun sorry to bother again. Any updates on the audit & official release? I see a lot of improvements/changes in this release and just wanted to ask if it is production ready to use already?

Thanks

**Comment by Joachim-Lebrun** [comment]
hi @sthapa-nyala , the audit of T-REX is on hold as long as the audit of ONCHAINID is not closed (as the security of ONCHAINID is an important part of the security of T-REX) but still, the code of T-REX should not change anymore (or very light changes). You can use the version of the software available on https://github.com/TokenySolutions/T-REX/tree/hacken-corrections as it should be the version used for the official release of the v4

**Comment by sthapa-nyala** [comment]
@Joachim-Lebrun Thank you very much.

**Comment by sthapa-nyala** [comment]
@Joachim-Lebrun Hello again. A quick question: 

On the Token contract now we have a parameter ONCHAINID.   
 *  @param _onchainID the address of the onchainID of the token

    // token details
    tokenDetails = {
      owner: tokeny,
      name: 'TREXDINO',
      symbol: 'TREX',
      decimals: 8,
      irs: '0x0000000000000000000000000000000000000000',
      ONCHAINID: '0x0000000000000000000000000000000000000042',
      irAgents: [tokeny, agent],
      tokenAgents: [tokeny, agent],
      complianceModules: [],
      complianceSettings: [],
    };

While creating a token or deploying token to trexfactory, it expects ONCHAINID of the token.

What exactly it is? and how can we get onchainID? Which contract needs to be used?

Thanks
