### ISSUE TITLE
Unable to Add Investors  OID address using "registerIdentity" in IDENTITYREGISTRY  contract.

### ISSUE THREAD

**Issue by wssranjula-cv** [TokenySolutions/T-REX#124]
I am implementing TREX using Remix. 

I cant use "registerIdentity" function on IDENTITYREGISTRY  contract it gives me a error. resun is "AgentRole: caller does not have the Agent role".

- I have deployed AgentRole contract and I added my Address using "AddAgent" function. 

- then I added the AgentRole contacts address to both IDENTITYREGISTRY and Token contracts using "addAgentOnIdentityRegistryContract"  and "addAgentOnTokenContract" functions.

what am i missing or doing wrong here? 

Thanks in Advance.

**Comment by Joachim-Lebrun** [comment]
Hi, you don't need to deploy the AgentRole contract, just the IdentityRegistry, as IdentityRegistry is implementing AgentRole, you can then add an agent directly on the IdentityRegistry smart contract / token smart contract, the Agent address can be either a wallet or a smart contract ,e.g. a multisig wallet from gnosis

**Comment by Joachim-Lebrun** [comment]
so instead of adding the AgentRole smart contract address through `addAgentOnIdentityRegistryContract` and `addAgentOnTokenContract` just add your wallet address, and then you can call the agent-scoped functions on the token and IdentityRegistry contracts
