### ISSUE TITLE
Would it be possible to create a bare-bones version of the repository without node.js specific files?

### ISSUE THREAD

**Issue by andras-ballai** [TokenySolutions/T-REX#140]
I'm working on a java project that seeks to create regulated security tokens and wants to use TREX as its basis. The only problem is that this repo contains files that aren't strictly part of the EIP-3643 specifications (files outside of the `contracts` folder). Would it be possible to publish a version that only contains the `contracts` folder and the necessary elements of `package.json`?

**Comment by Joachim-Lebrun** [comment]
Hi @andras-ballai , we need to keep the javascript files on the repository as they are necessary for the testing of the smart contracts, it is super important for the security of a solidity project to have a good test coverage on all contracts and to run the tests at every update of the repository files to ensure nothing was broken with the update. 
If you want to simply extract the contract folder you can do so and use it as such in your project though...
