### ISSUE TITLE
VM Exception on running the factory test

### ISSUE THREAD

**Issue by jeet-scd** [TokenySolutions/T-REX#151]
On running the factory test file using this command: `truffle test test/factory.test.js` 
the following error occurs

![image](https://github.com/TokenySolutions/T-REX/assets/125538250/27f18805-daac-43e8-8b82-d06b8c3738cc)

**Comment by Joachim-Lebrun** [comment]
Hi @jeet-scd , normally all tests are supposed to pass as they do on the actions on each push, e.g. https://github.com/TokenySolutions/T-REX/actions/runs/4808613161/jobs/8558808727 for the last push of main branch. 
However we are aware that truffle, while having been a very good tool for solidity developers in the past, is now becoming obsolete and generate random bugs when running tests, this is why we decided to switch to hardhat for our dev environment, you should use the version of the protocol currently on the [develop branch](https://github.com/TokenySolutions/T-REX/tree/develop) which is using hardhat for all the tests and for compilation
