### ISSUE TITLE
Single Identity registry storage(irs) setup

### ISSUE THREAD

**Issue by ainayat1914** [TokenySolutions/T-REX#193]
I am working on a scenario to use single IRS for multiple tokens. I tried to deploy a new token by passing IRS parameter in the call. 
But it alway gives me same error: RPC Error :  execution reverted: Ownable: caller is not the owner
I tried to dig into the contract logic but couldn't find anything.
Although in Trex whitepaper I read that its possible.
Any ideas or things I might be missing here?

**Comment by Joachim-Lebrun** [comment]
Hello @ainayat1914 , it is indeed possible to use the same Identity Registry Storage (IRS) with 2 tokens, see the example here :
- i created a new token with a new IRS in this transaction https://mumbai.polygonscan.com/tx/0xd7cdf889b01accebd9d19e916df3c8110cf4c96af64353bbfdfe33a4f7280982 
- i created another token with the IRS of the token created earlier in this transaction https://mumbai.polygonscan.com/tx/0x792ddc078089fe05aef6db312713fb15f55a392a488681a79fe79a9223199f8f

Both tokens share the same IRS. The tokens were deployed through the TREXFactory contract via the TREXGateway available here https://mumbai.polygonscan.com/address/0xd54555fFE57ba4255DafaaBA41449152d019Bd53#code 
I activated public deployments on that Gateway, so you can deploy tokens from it if you want to make some tests, the limitations for addresses that are not whitelisted as deployers/agents on the gateway are that you can only deploy for yourself, i.e. Owner address that you specify in the deployTREXSuite function has to be the address with which you call the smart contract

**Comment by ainayat1914** [comment]
Hi @Joachim-Lebrun 

Thanks for the response. But unfortunately, we are still using the old implementation in which we are deploying all the contracts seperately without the TREXGateway. Our implementation looks something like this:
`
const salt = 'some_generated_salt';
const claimDetails = {
      claimTopics: [7],
      issuers: [jsonBody.contract_address_claimissuer],
      issuerClaims: [[7]],
    };
const tokenDetails = {
      owner: issuer,
      name: jsonBody.token_name,
      symbol: jsonBody.token_symbol,
      decimals: jsonBody.token_decimal,
      irs: "0x0000000000000000000000000000000000000000",
      ONCHAINID: "0x0000000000000000000000000000000000000000",
      irAgents: [issuer, jsonBody.agent_address],
      tokenAgents: [issuer, jsonBody.agent_address],
      complianceModules: [],
      complianceSettings: [],
    };
const deployTx = newContractInstance.methods.deployTREXSuite(
    salt,
    tokenDetails,
    claimDetails
  );
`

**Comment by Joachim-Lebrun** [comment]
by default the IRS ownership is kept by the factory, to be able to re-use it with new tokens that are deployed by the factory, as it requires Owner role to call the `bindIdentityRegistry` function on IRS. The Factory has a function `recoverContractOwnership` that allows the Owner of the Factory to get back the ownership of IRS contract post deployment is necessary, this way it is possible to manually bind a new IR to the IRS. But normally, if the ownership of the IRS you deployed is still belonging to the factory you should be able to add its address as a parameter on a new deployment. 
Are you sure that you give the right address? the IRS address you have to provide is the address of the proxy that is deployed when you call `deployTREXSuite` and of which the address is given in the event emitted by the deployment `TREXSuiteDeployed(address(token), address(ir), address(irs), address(tir), address(ctr), address(mc), _salt)` 
you can find it easily by listening the event like this :

```
deployTx.send({ from: senderAddress })
  .on('receipt', receipt => {
    const trexSuiteDeployedEvent = receipt.events.TREXSuiteDeployed;
    if (trexSuiteDeployedEvent) {
      const irsAddress = trexSuiteDeployedEvent.returnValues.irs;
      console.log('IRS Address:', irsAddress);
    }
  })
  .on('error', console.error);
```
or by calling functions on smart contracts like this (given the setup you give above): 

```
const tokenAddress = await newContractInstance.methods.getToken(salt);
const token = await ethers.getContractAt('Token', tokenAddress);
const irAddress = await token.identityRegistry();
const ir = await ethers.getContractAt('IdentityRegistry', irAddress);
const irsAddress = await ir.identityStorage();
```

**Comment by ainayat1914** [comment]
Hi again @Joachim-Lebrun 
First thanks for the reply

I think I get it where I might be wrong.
I'll try to explain my scenario a bit more detailed.
I have a token already deployed with 2 main wallets(Issuer and ClaimIssuer)

From Issuer I deployed these contracts:
- Claim Topics Registry(CTR)
- Trusted Issuer Registry(TIR)
- Identity Registry (IR)
- Identity Registry Storage (IRS)
- Modular Compliance (MC)
- TKNINS
- TREXImplAuth
- TrexFactory
- Token

From Claim issuer i deployed only
- Claim issuer contract

Then I have agent wallet and distributor wallet which are being used for identity deployment/identity registry and distribution of tokens.

For the new token I deployed everything from a new Issuer and new Claim issuer except I tried to use IR and IRS from above token. Which didn't work.
From your answers what I get is I have to deploy token from the same Factory not from seperate factories and to deploy factory I also have to deploy all these or some of these contracts from single set of Issuer and ClaimIssuer wallets or no?

**Comment by Joachim-Lebrun** [comment]
You should indeed use a single Factory contract, and to be able to use an existing IRS on a token deployed by the factory you should transfer the ownership of that IRS to the factory you want to deploy your token from. 
If you need to recover the ownership of that IRS later on you can do it through the interface of the Factory, but then you will not be able to use that IRS on new tokens anymore, as long as the ownership of IRS is not given to the Factory

**Comment by ainayat1914** [comment]
Thanks again for the clarification.
Just 1 last question, what will happen when there are new updates for the contracts? For example in the future there will be new updates for the factory, old factory will be obsolete. Correct?
