### ISSUE TITLE
TREX factory contract  deployment flow

### ISSUE THREAD

**Issue by aqeelVaival** [TokenySolutions/T-REX#227]
So i was trying to understand the deployment flow for TREXFactory contract.. We have 2 params in it
address implementationAuthority_,
address idFactory_

There are 2 type of ways in my mind:
1:
implementationAuthority_  should be the address of **REX/Contract/Proxy/authority/TREXImplementationAuthority.sol**
![image](https://github.com/user-attachments/assets/af244fd8-9785-4f35-8c12-6988dec96c2a)

idFactory_ should be the address of **ONCHAINID/contract/factory/IdFactory.sol**

IdFactory.sol can be deployed from onchainid repo and we can get the address whereas  for the deployment of TREXImplementationAuthority.sol we need :

**bool referenceStatus, address trexFactory, address iaFactory**
![image](https://github.com/user-attachments/assets/5c1ce0fe-b971-4d5c-9ecd-239ff49900bf)

if we consider referenceStatus=true then trexFactory can be 0x..but still we need to have iaFactory address.
so for **iaFactory** contract deployment we again needed address trexFactory
![image](https://github.com/user-attachments/assets/b967db1f-bdc3-4319-85ed-2e8c4fc84346)

how can we provide  trexFactory address , which is not deployed yet..or to pass 0x ???

2:
implementationAuthority_  should be the address of ONCHAINID/Contract/Proxy/ImplementationAuthority.sol
idFactory_ should be the address of ONCHAINID/contract/factory/IdFactory.sol

if this is the case then its fine...whereas i have one more confusion but i guess i should put it at ONCHAINID .

**Comment by Joachim-Lebrun** [comment]
indeed, the first time you deploy the whole suite you won't have an address to give to TREXImplementationAuthority for the IAFactory and TREXFactory, this constructor parameters are used by the IA factory to deploy secondary TREXImplementationAuthority contracts, or can be useful if you decide to change the main TREXImplementationAuthority later on with an existing TREXFactory and IAFactory, but for the initial main TREXImplementationAuthority you will have to use the 0x... addresses for both contracts in the constructor as you don't have the addresses yet. Could seem a bit counter-intuitive but it is useful to have these constructor parameters for the contracts generated by IAFactory when the token owner want to get their own TREXImplementationAuthority contract. 
For IdFactory i answered on the issue you dropped on the OID repo
