### ISSUE TITLE
Mint 0

### ISSUE THREAD

**Issue by Aboudjem** [TokenySolutions/T-REX#55]
https://github.com/TokenySolutions/T-REX/blob/a8a9e8fa12eb4c523fa797007ad320c1e06d2b5b/contracts/token/TransferManager.sol#L263

It should be impossible to mint 0 tokens?

**Comment by Joachim-Lebrun** [comment]
why not? it's not a real problem and adding a `require` would add some gas cost to the transaction, additionally, minting 0 tokens could be used to check if the function is working well without impacting the token supply

**Comment by Aboudjem** [comment]
>minting 0 tokens could be used to check if the function is working well without impacting the token supply
We have a tons of functions for this purpose.
