### ISSUE TITLE
Centralized exchanges - pooled vs investor wallets - settlement time

### ISSUE THREAD

**Issue by flojdek** [TokenySolutions/T-REX#57]
So in your whitepaper (https://tokeny.com/wp-content/uploads/2018/12/t-rex-whitepaper.pdf), you mention that pooled wallets are not appropriate for security token exchanges (if I understand correctly) and it's hard to disagree in general. Mingling funds together is never a good idea as opposed to segregation. It does create an issue though if the `transfer` function will need to be called with every transaction surely that will limit the speed of trading considerably with the current transactions speeds. If I just bought 100 tokens I can't just turn around and sell them until the previous buy transaction is settled. It is good to a high degree because speculation on the market place will be smaller, funds being withdrawn will always be your funds, and there should be less reconciliation problems etc. but I was just wondering what's your take on that problem! Cheers.

**Comment by Joachim-Lebrun** [comment]
Hi @flojdek you understood well about the pooled wallets issue, in facts TREX is intended to be used only by decentralized exchanges as the `transfer` function wouldn't be called by a centralized exchange (everything happening on a database and tokens being put on a pooled wallet), therefore if the `transfer`function is not called the whole compliance validation system (including checks on `IdentityRegistry`, on `TrustedIssuersRegistry`, on `ClaimTopicsRegistry`, on `Compliance` and on the `onchainID` of the investor wouldn't be made at the transfer time, which could also be a problem at the time of withdrawal from the exchange. The idea is not to enable high frequence trading on the TREX tokens, at least not at the moment, and if this is needed in the future i am sure we would find a solution for this. At the moment the transaction speed on DEX for a TREX token is approximately the same as any ERC20 token which is quite enough for the use case. 
Cheers.
