### ISSUE TITLE
🐛 Issue with identity verification.

### ISSUE THREAD

**Issue by Nakasar** [TokenySolutions/T-REX#73]
**Type:** 🐛 _Bug_

**Contracts:** IdentityRegistry

**Details:**
The validation of an identity expect claims to be verified.
I suspect the expected flow is supposed to be if for each topic, if at least one claim emitted by a trusted claim issuer is valid, then the identity is valid.

However, the code found here:
https://github.com/TokenySolutions/T-REX/blob/35a97c67888b030d4389a2a5005cd13ca757a585/contracts/registry/IdentityRegistry.sol#L148-L185

Implies that for a given topic, each claim on the identity is verified in order, if any is not verified, the verification stops and return false, without attempting to verify other claims.

**Expected behavior:**
It should perform verification on all claims found until a valid one is found, and return false only after all claims were checked.

**Comment by Joachim-Lebrun** [comment]
issue fixed in commit https://github.com/TokenySolutions/T-REX/commit/7f73ff2415cff3d1a9becdb67ee05f6ef797931e
